[package]
name = "qb2or"
version = "0.1.0"
authors = ["Henrik Pejer <mrpejer@gmail.com>"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies ]
image = "0.22.3"
